/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.jni;

public class androidcameraJNI {
  public final static native long new_CompVCameraAndroidProxy();
  public final static native void delete_CompVCameraAndroidProxy(long jarg1);
  public final static native void CompVCameraAndroidProxy_setCallbackFunc(long jarg1, CompVCameraAndroidProxy jarg1_, long jarg2, long jarg3);
  public final static native boolean CompVCameraAndroidProxy_pushFrame(long jarg1, CompVCameraAndroidProxy jarg1_, java.nio.ByteBuffer jarg2, long jarg3, long jarg4, long jarg5, int jarg6, int jarg7);
}
