/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.jni;

public interface androidcameraConstants {
  public final static String COMPV_CAMERA_ANDROID_LOG_TAG = androidcameraJNI.COMPV_CAMERA_ANDROID_LOG_TAG_get();
}
