/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.jni;

public class CompVCameraAndroidProxy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CompVCameraAndroidProxy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CompVCameraAndroidProxy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        androidcameraJNI.delete_CompVCameraAndroidProxy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CompVCameraAndroidProxy() {
    this(androidcameraJNI.new_CompVCameraAndroidProxy(), true);
  }

  public void setCallbackFunc(long funcptr, long userData) {
    androidcameraJNI.CompVCameraAndroidProxy_setCallbackFunc(swigCPtr, this, funcptr, userData);
  }

  public boolean pushFrame(java.nio.ByteBuffer frameDataPtr, long frameDataSize, long frameWidth, long frameHeight, int frameFps, int framePixelFormat) {
    return androidcameraJNI.CompVCameraAndroidProxy_pushFrame(swigCPtr, this, frameDataPtr, frameDataSize, frameWidth, frameHeight, frameFps, framePixelFormat);
  }

}
